/* Generated by scripts/development/generate_openapi_types.py */
/* Run uv run python scripts/development/generate_openapi_types.py to update */

export interface components {
  "schemas": {
    "AgentType": "explorer" | "analyst" | "reviewer";
    "Attachment": {
      "description"?: (string | null);
      "f_path": string;
      "media_type"?: (string | null);
    };
    "AttachmentReference": {
      "f_path": string;
    };
    "Body_api_upload_attachment_api_v1_chat_attachment_upload_post": {
      "conversation_id": string;
      "file": string;
    };
    "ChatStreamDoneEvent": {
      "type": "done";
    };
    "ChatStreamErrorEvent": {
      "content": string;
      "type": "error";
    };
    "ChatStreamEvent": (components["schemas"]["ChatStreamMessageEvent"] | components["schemas"]["ChatStreamThinkingEvent"] | components["schemas"]["ChatStreamMessageDeltaEvent"] | components["schemas"]["ChatStreamErrorEvent"] | components["schemas"]["ChatStreamDoneEvent"] | components["schemas"]["ChatStreamSubagentMessageEvent"] | components["schemas"]["ChatStreamSubagentThinkingEvent"] | components["schemas"]["ChatStreamSubagentMessageDeltaEvent"] | components["schemas"]["ChatStreamSubagentStatusEvent"]);
    "ChatStreamMessageDeltaEvent": {
      "delta": string;
      "message_id": string;
      "reset"?: boolean;
      "type": "message_delta";
    };
    "ChatStreamMessageEvent": {
      "message": components["schemas"]["MessageResponse"];
      "type": "message";
    };
    "ChatStreamRequest": {
      "conversation_id": string;
      "message": components["schemas"]["UserMessageRequest"];
    };
    "ChatStreamSubagentMessageDeltaEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "delegation_id": string;
      "delta": string;
      "instruction"?: (string | null);
      "message_id": string;
      "parent_tool_call_id"?: (string | null);
      "reset"?: boolean;
      "session_id": string;
      "type": "subagent_message_delta";
    };
    "ChatStreamSubagentMessageEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "delegation_id": string;
      "instruction"?: (string | null);
      "message": components["schemas"]["MessageResponse"];
      "parent_tool_call_id"?: (string | null);
      "session_id": string;
      "type": "subagent_message";
    };
    "ChatStreamSubagentStatusEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "delegation_id": string;
      "instruction"?: (string | null);
      "parent_tool_call_id"?: (string | null);
      "session_id": string;
      "status": "running" | "completed" | "needs_repair" | "failed" | "cancelled";
      "type": "subagent_status";
    };
    "ChatStreamSubagentThinkingEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "delegation_id": string;
      "delta": string;
      "instruction"?: (string | null);
      "message_id": string;
      "parent_tool_call_id"?: (string | null);
      "reset"?: boolean;
      "session_id": string;
      "type": "subagent_thinking";
    };
    "ChatStreamThinkingEvent": {
      "delta": string;
      "message_id": string;
      "reset"?: boolean;
      "type": "thinking";
    };
    "ConversationListResponse": {
      "conversations": Array<components["schemas"]["ConversationResponse"]>;
    };
    "ConversationResponse": {
      "conversation_id": string;
      "running": boolean;
      "title": string;
      "update_at": string;
    };
    "ConversationRunStatusResponse": {
      "running": boolean;
    };
    "CreateConversationRequest": {
      "initial_message"?: (string | null);
      "is_draft"?: boolean;
    };
    "DeleteAttachmentRequest": {
      "conversation_id": string;
      "f_path": string;
    };
    "DeleteConversationRequest": {
      "conversation_ids": Array<string>;
    };
    "EvalDelegationResponse": {
      "agent_type": components["schemas"]["AgentType"];
      "analysis_id": string;
      "attachments"?: (Array<components["schemas"]["Attachment"]> | null);
      "delegation_id": string;
      "message": string;
      "result"?: ({
        [key: string]: unknown;
      } | null);
      "session_id": string;
    };
    "ImageContent": {
      "image_url": string;
      "type": "image_url";
    };
    "MessageListResponse": {
      "messages": Array<components["schemas"]["MessageResponse"]>;
    };
    "MessageResponse": {
      "attachments"?: (Array<components["schemas"]["Attachment"]> | null);
      "created_at"?: (string | null);
      "eval_delegations"?: (Array<components["schemas"]["EvalDelegationResponse"]> | null);
      "finish_reason"?: (string | null);
      "message_id"?: (string | null);
      "parts": Array<(components["schemas"]["TextContent"] | components["schemas"]["ImageContent"] | components["schemas"]["ThinkingContent"] | components["schemas"]["ToolCallPart"] | components["schemas"]["ToolResultPart"])>;
      "role": "user" | "assistant" | "tool" | "system";
    };
    "ProblemDetails": {
      "detail"?: (string | null);
      "instance"?: (string | null);
      "status": number;
      "title": string;
      "type": string;
      [key: string]: unknown;
    };
    "SubagentMessageListResponse": {
      "messages": Array<components["schemas"]["MessageResponse"]>;
      "status": "running" | "completed" | "needs_repair" | "failed" | "cancelled";
    };
    "TextContent": {
      "text": string;
      "type": "text";
    };
    "ThinkingContent": {
      "status"?: "streaming" | "complete" | "interrupted";
      "text": string;
      "type": "thinking";
    };
    "ToolCallPart": {
      "args"?: {
        [key: string]: unknown;
      };
      "name": string;
      "tool_call_id": string;
      "type": "tool_call";
    };
    "ToolResultPart": {
      "content": string;
      "name": string;
      "tool_call_id": string;
      "type": "tool_result";
    };
    "UpdateConversationRequest": {
      "conversation_id": string;
      "title": string;
    };
    "UploadAttachmentResponse": {
      "attachment": components["schemas"]["Attachment"];
    };
    "UserMessageRequest": {
      "attachments"?: (Array<components["schemas"]["AttachmentReference"]> | null);
      "parts": Array<(components["schemas"]["TextContent"] | components["schemas"]["ImageContent"])>;
    };
    "UserResponse": {
      "doris_role_name": string;
      "id": number;
      "username": string;
    };
  };
}

export interface operations {
  "api_create_conversation_api_v1_chat_create_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["CreateConversationRequest"];
    };
    "responses": {
      "201": {
        "content": {
        "application/json": components["schemas"]["ConversationResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_delete_attachment_api_v1_chat_attachment_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["DeleteAttachmentRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_delete_conversations_api_v1_chat_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["DeleteConversationRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_delete_draft_conversation_api_v1_chat_draft__conversation_id__delete": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_attachment_api_v1_chat_attachment_get_get": {
    "parameters": {
      "path"?: never;
      "query": {
        "conversation_id": string;
        "f_path": string;
      };
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_conversation_run_status_api_v1_chat__conversation_id__run_get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ConversationRunStatusResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_conversations_api_v1_chat_ls_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ConversationListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_messages_api_v1_chat_ls__conversation_id__get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["MessageListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_subagent_messages_api_v1_chat__conversation_id__subagents__analysis_id___agent_type___session_id__runs__delegation_id__messages_get": {
    "parameters": {
      "path": {
        "agent_type": "explorer" | "analyst" | "reviewer";
        "analysis_id": string;
        "conversation_id": string;
        "delegation_id": string;
        "session_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["SubagentMessageListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_resume_chat_api_v1_chat__conversation_id__resume_post": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_stop_conversation_run_api_v1_chat__conversation_id__stop_post": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_stream_chat_api_v1_chat_stream_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["ChatStreamRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ChatStreamEvent"];
        "text/event-stream": components["schemas"]["ChatStreamEvent"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_subscribe_conversation_run_api_v1_chat__conversation_id__events_get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_update_conversation_api_v1_chat_update_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["UpdateConversationRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_upload_attachment_api_v1_chat_attachment_upload_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "multipart/form-data": components["schemas"]["Body_api_upload_attachment_api_v1_chat_attachment_upload_post"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["UploadAttachmentResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_users_api_v1_users_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["UserResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
}

export interface paths {
  "/api/v1/chat/attachment/delete": {
    "post": operations["api_delete_attachment_api_v1_chat_attachment_delete_post"];
  };
  "/api/v1/chat/attachment/get": {
    "get": operations["api_get_attachment_api_v1_chat_attachment_get_get"];
  };
  "/api/v1/chat/attachment/upload": {
    "post": operations["api_upload_attachment_api_v1_chat_attachment_upload_post"];
  };
  "/api/v1/chat/create": {
    "post": operations["api_create_conversation_api_v1_chat_create_post"];
  };
  "/api/v1/chat/delete": {
    "post": operations["api_delete_conversations_api_v1_chat_delete_post"];
  };
  "/api/v1/chat/draft/{conversation_id}": {
    "delete": operations["api_delete_draft_conversation_api_v1_chat_draft__conversation_id__delete"];
  };
  "/api/v1/chat/ls": {
    "get": operations["api_get_conversations_api_v1_chat_ls_get"];
  };
  "/api/v1/chat/ls/{conversation_id}": {
    "get": operations["api_get_messages_api_v1_chat_ls__conversation_id__get"];
  };
  "/api/v1/chat/stream": {
    "post": operations["api_stream_chat_api_v1_chat_stream_post"];
  };
  "/api/v1/chat/update": {
    "post": operations["api_update_conversation_api_v1_chat_update_post"];
  };
  "/api/v1/chat/{conversation_id}/events": {
    "get": operations["api_subscribe_conversation_run_api_v1_chat__conversation_id__events_get"];
  };
  "/api/v1/chat/{conversation_id}/resume": {
    "post": operations["api_resume_chat_api_v1_chat__conversation_id__resume_post"];
  };
  "/api/v1/chat/{conversation_id}/run": {
    "get": operations["api_get_conversation_run_status_api_v1_chat__conversation_id__run_get"];
  };
  "/api/v1/chat/{conversation_id}/stop": {
    "post": operations["api_stop_conversation_run_api_v1_chat__conversation_id__stop_post"];
  };
  "/api/v1/chat/{conversation_id}/subagents/{analysis_id}/{agent_type}/{session_id}/runs/{delegation_id}/messages": {
    "get": operations["api_get_subagent_messages_api_v1_chat__conversation_id__subagents__analysis_id___agent_type___session_id__runs__delegation_id__messages_get"];
  };
  "/api/v1/users": {
    "get": operations["list_users_api_v1_users_get"];
  };
}
