/* Generated by scripts/development/generate_openapi_types.py */
/* Run uv run python scripts/development/generate_openapi_types.py to update */

export interface components {
  "schemas": {
    "AgentType": "explorer" | "analyst" | "reviewer";
    "Attachment": {
      "description"?: (string | null);
      "f_path": string;
      "media_type"?: (string | null);
    };
    "ChatStreamDoneEvent": {
      "type": "done";
    };
    "ChatStreamErrorEvent": {
      "content": string;
      "type": "error";
    };
    "ChatStreamEvent": (components["schemas"]["ChatStreamMessageEvent"] | components["schemas"]["ChatStreamThinkingEvent"] | components["schemas"]["ChatStreamMessageDeltaEvent"] | components["schemas"]["ChatStreamErrorEvent"] | components["schemas"]["ChatStreamDoneEvent"] | components["schemas"]["ChatStreamSubagentStatusEvent"]);
    "ChatStreamMessageDeltaEvent": {
      "delta": string;
      "message_id": string;
      "reset"?: boolean;
      "type": "message_delta";
    };
    "ChatStreamMessageEvent": {
      "message": components["schemas"]["MessageResponse"];
      "type": "message";
    };
    "ChatStreamRequest": {
      "conversation_id": string;
      "message": components["schemas"]["UserMessageRequest"];
    };
    "ChatStreamSubagentStatusEvent": {
      "agent_type": components["schemas"]["AgentType"];
      "delegation_id": string;
      "status": "running" | "completed" | "failed" | "cancelled";
      "type": "subagent_status";
    };
    "ChatStreamThinkingEvent": {
      "delta": string;
      "message_id": string;
      "reset"?: boolean;
      "type": "thinking";
    };
    "ConversationListResponse": {
      "conversations": Array<components["schemas"]["ConversationResponse"]>;
    };
    "ConversationResponse": {
      "conversation_id": string;
      "running": boolean;
      "title": string;
      "update_at": string;
    };
    "ConversationRunStatusResponse": {
      "running": boolean;
    };
    "CreateConversationRequest": {
      "initial_message"?: (string | null);
      "is_draft"?: boolean;
    };
    "DeleteConversationRequest": {
      "conversation_ids": Array<string>;
    };
    "ImageContent": {
      "image_url": string;
      "type": "image_url";
    };
    "MessageListResponse": {
      "messages": Array<components["schemas"]["MessageResponse"]>;
    };
    "MessageResponse": {
      "attachments"?: (Array<components["schemas"]["Attachment"]> | null);
      "finish_reason"?: (string | null);
      "message_id"?: (string | null);
      "parts": Array<(components["schemas"]["TextContent"] | components["schemas"]["ImageContent"] | components["schemas"]["ThinkingContent"] | components["schemas"]["ToolCallPart"] | components["schemas"]["ToolResultPart"])>;
      "role": "user" | "assistant" | "tool" | "system";
    };
    "ProblemDetails": {
      "detail"?: (string | null);
      "instance"?: (string | null);
      "status": number;
      "title": string;
      "type": string;
      [key: string]: unknown;
    };
    "TextContent": {
      "text": string;
      "type": "text";
    };
    "ThinkingContent": {
      "status"?: "streaming" | "complete" | "interrupted";
      "text": string;
      "type": "thinking";
    };
    "ToolCallPart": {
      "args"?: {
        [key: string]: unknown;
      };
      "name": string;
      "tool_call_id": string;
      "type": "tool_call";
    };
    "ToolResultPart": {
      "content": string;
      "name": string;
      "tool_call_id": string;
      "type": "tool_result";
    };
    "UserMessageRequest": {
      "parts": Array<(components["schemas"]["TextContent"])>;
    };
    "UserResponse": {
      "doris_role_name": string;
      "id": number;
      "username": string;
    };
  };
}

export interface operations {
  "api_create_conversation_api_v1_chat_create_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["CreateConversationRequest"];
    };
    "responses": {
      "201": {
        "content": {
        "application/json": components["schemas"]["ConversationResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_delete_conversations_api_v1_chat_delete_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["DeleteConversationRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_attachment_api_v1_chat_attachment_get_get": {
    "parameters": {
      "path"?: never;
      "query": {
        "conversation_id": string;
        "f_path": string;
      };
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": unknown;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_conversation_run_status_api_v1_chat__conversation_id__run_get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ConversationRunStatusResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_conversations_api_v1_chat_ls_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ConversationListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_get_messages_api_v1_chat_ls__conversation_id__get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["MessageListResponse"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_resume_chat_api_v1_chat__conversation_id__resume_post": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_stop_conversation_run_api_v1_chat__conversation_id__stop_post": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "204": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_stream_chat_api_v1_chat_stream_post": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody": {
      "application/json": components["schemas"]["ChatStreamRequest"];
    };
    "responses": {
      "200": {
        "content": {
        "application/json": components["schemas"]["ChatStreamEvent"];
        "text/event-stream": components["schemas"]["ChatStreamEvent"];
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "api_subscribe_conversation_run_api_v1_chat__conversation_id__events_get": {
    "parameters": {
      "path": {
        "conversation_id": string;
      };
      "query"?: never;
      "header": {
        "X-User-ID"?: (number | null);
      };
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": never;
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
  "list_users_api_v1_users_get": {
    "parameters": {
      "path"?: never;
      "query"?: never;
      "header"?: never;
      "cookie"?: never;
    };
    "requestBody"?: never;
    "responses": {
      "200": {
        "content": {
        "application/json": Array<components["schemas"]["UserResponse"]>;
      };
      };
      "422": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
      "default": {
        "content": {
        "application/json": components["schemas"]["ProblemDetails"];
        "application/problem+json": components["schemas"]["ProblemDetails"];
      };
      };
    };
  };
}

export interface paths {
  "/api/v1/chat/attachment/get": {
    "get": operations["api_get_attachment_api_v1_chat_attachment_get_get"];
  };
  "/api/v1/chat/create": {
    "post": operations["api_create_conversation_api_v1_chat_create_post"];
  };
  "/api/v1/chat/delete": {
    "post": operations["api_delete_conversations_api_v1_chat_delete_post"];
  };
  "/api/v1/chat/ls": {
    "get": operations["api_get_conversations_api_v1_chat_ls_get"];
  };
  "/api/v1/chat/ls/{conversation_id}": {
    "get": operations["api_get_messages_api_v1_chat_ls__conversation_id__get"];
  };
  "/api/v1/chat/stream": {
    "post": operations["api_stream_chat_api_v1_chat_stream_post"];
  };
  "/api/v1/chat/{conversation_id}/events": {
    "get": operations["api_subscribe_conversation_run_api_v1_chat__conversation_id__events_get"];
  };
  "/api/v1/chat/{conversation_id}/resume": {
    "post": operations["api_resume_chat_api_v1_chat__conversation_id__resume_post"];
  };
  "/api/v1/chat/{conversation_id}/run": {
    "get": operations["api_get_conversation_run_status_api_v1_chat__conversation_id__run_get"];
  };
  "/api/v1/chat/{conversation_id}/stop": {
    "post": operations["api_stop_conversation_run_api_v1_chat__conversation_id__stop_post"];
  };
  "/api/v1/users": {
    "get": operations["list_users_api_v1_users_get"];
  };
}
