[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncmy>=0.2.11",
    "cos-python-sdk-v5>=1.9.41",
    "cryptography>=46.0.4",
    "deepagents>=0.3.11",
    "faker>=40.4.0",
    "fastapi[standard]>=0.128.0",
    "loguru>=0.7.3",
    "omegaconf>=2.3.0",
    "openai>=2.16.0",
    "pymysql>=1.1.2",
    "sqlacodegen>=3.2.0",
    "sqlalchemy>=2.0.46",
]
