log:
  level: INFO # 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  rotation: 10MB # 日志文件滚动大小

doris:
  host: 127.0.0.1
  port: 9030
  user: atguigu
  password: ${oc.env:DORIS_PASSWORD}
  database: ecommerce

meta_postgresql:
  host: 127.0.0.1
  port: 5432
  user: atguigu
  password: ${oc.env:POSTGRES_PASSWORD}
  database: meta

langgraph_postgresql:
  host: 127.0.0.1
  port: 5432
  user: atguigu
  password: ${oc.env:POSTGRES_PASSWORD}
  database: langgraph

elasticsearch:
  host: 127.0.0.1
  port: 9200
  column_index: data-agent-column
  metric_index: data-agent-metric
  value_index: data-agent-value
  embedding_size: 1024

embedding:
  base_url: https://api.siliconflow.cn/v1
  api_key: ${oc.env:SILICONFLOW_API_KEY}
  model: BAAI/bge-m3
  timeout: 30.0

lm_config:
  active: deepseek-v4-flash-openrouter
  models:
    deepseek-v4-flash-openrouter:
      model: deepseek/deepseek-v4-flash-0731
      base_url: https://openrouter.ai/api/v1
      api_key: ${oc.env:OPENROUTER_API_KEY}
      params: {}
      profile:
        max_input_tokens: 1048576 # 模型上下文长度，用于计算对话压缩阈值
    qwen3.6-plus-openrouter:
      model: qwen/qwen3.7-flash
      base_url: https://openrouter.ai/api/v1
      api_key: ${oc.env:OPENROUTER_API_KEY}
      params: {}
      profile:
        max_input_tokens: 1000000 # 模型上下文长度，用于计算对话压缩阈值

mcp: # 格式参考：https://docs.langchain.com/oss/python/langchain/mcp#transports
  tavily:
    transport: streamable_http
    url: https://mcp.tavily.com/mcp/?tavilyApiKey=${oc.env:TAVILY_API_KEY}

cors_origins: []

port: 7000
