"""Docker 沙箱的资源限制与生命周期参数。"""

# 同一 Docker 主机上的独立部署应使用不同命名空间。
DEPLOYMENT_NAMESPACE = "local"
OWNERSHIP_REDIS_URL = "redis://127.0.0.1:6379/2"
OWNERSHIP_LOCK_TIMEOUT_SECONDS = 60
OWNERSHIP_WAIT_TIMEOUT_SECONDS = 60
OWNERSHIP_LEASE_SECONDS = 30

IMAGE = "dataagent-sandbox:latest"
NETWORK_MODE = "none"
MEMORY_LIMIT = "2g"
NANO_CPUS = 2_000_000_000
PIDS_LIMIT = 256
INTERNAL_COMMAND_TIMEOUT_SECONDS = 60
MAX_FILE_BYTES = 50 * 1024 * 1024
MAX_USER_STORAGE_BYTES = 1024 * 1024 * 1024
VOLUME_DRIVER = "local"
# local 驱动不支持硬配额；支持配额的驱动可引用 {max_user_storage_bytes}。
VOLUME_DRIVER_OPTIONS: dict[str, str] = {}

MAX_RUNNING_CONTAINERS = 8
IDLE_STOP_SECONDS = 600
IDLE_REMOVE_SECONDS = 3600
CLEANUP_INTERVAL_SECONDS = 60
CLEANUP_FAILURE_ALERT_THRESHOLD = 3
STOP_CONTAINERS_ON_SHUTDOWN = True
